### ISSUE TITLE
【誤植でしょうか：初版】第２章 P.51 9行目

### ISSUE THREAD

**Issue by takikuchi** [YutaroOgawa/causal_book#13]
「【誤植修正：初版】第4章 P. 81 とp. 82の導出 誤植」のissueの内容に基づくと、第２章p.51 9行目は下記の誤植でしょうか。

P(y|z) = Sigma_x P(y | z, x) × P(x|z) 
　↓
P(y|z) = Sigma_x P(y | z, x) × P(x) 

同ページのこれ以降の数式も変わりますでしょうか。

**Comment by YutaroOgawa** [comment]
@takikuchi さま

誠にありがとうございます。

式導出の流れはいろいろな方向から攻めれるので、悩ましいのですが、

[1] Issue https://github.com/YutaroOgawa/causal_book/issues/11の後半、
「第4章 p.82 傾向スコアとは 一番最後の式までの導出手順」
については、調整化公式を変形していっていますが、
ここでは、条件付き確率と同時確率の変換ではなく、
右辺の分子分母に、 P(Z=z | X=x)をかけ算するのがすっきりします。
（書籍は現状では分かりづらすぎる）

[2] 第2章2-4 調整化公式とは P.51 9行目の
P(y|z) = Sigma_x P(y|z,x) * P(x|z)
ですが、この節では調整化公式そのものを求めています。

条件付き確率を同時確率に変換する場合、例えばP(y)であれば、

P(y) = Sigma_x P(y|x) * P(x)

です。ここでP.51 9行目のように、左辺がzでの条件付き確率 P(y|z) であった場合には
全てにzの条件付きが入るため、

P(y|z) = Sigma_x P(y|z,x) * P(x|z)

となります。

こちらが、p.51の9行目となっております。

私自身が混乱し、回答が一変二変してご迷惑をおかけし、大変申し訳ございません。
どうぞよろしくお願いいたします。

**Comment by takikuchi** [comment]
ご回答ありがとうございました。
調整化公式とベイズの定理を混同していたことが分かりました。

**Comment by YutaroOgawa** [comment]
@takikuchi さま

このあたり、式できちんと導出していくのは、難しい部分です。
私も再度見直し、非常に整理できました。

誠にありがとうございました。

回答がいろいろと不手際でお手数をおかけし、申し訳ございませんでした。
今後とも、どうぞ宜しくお願い致します。
