### ISSUE TITLE
P82での数式についての質問です。【訂正範囲：p. 82　4行目～18行目の数式展開】

### ISSUE THREAD

**Issue by KENJI-JIN** [YutaroOgawa/causal_book#24]
第3版を読んでいます。
4行目の数式で
![image](https://user-images.githubusercontent.com/60377218/111737681-62a65400-88c3-11eb-9651-248a87e81c8c.png)
と書かれているのですが、分母と分子に同じものが入っているので
![image](https://user-images.githubusercontent.com/60377218/111737808-9bdec400-88c3-11eb-8691-f55c98b90f78.png)
となりますよね。これはあっているのでしょうか？

↓ではないのかなと思っています。
![image](https://user-images.githubusercontent.com/60377218/111738032-fe37c480-88c3-11eb-9c7f-b7cd6243b800.png)

**Comment by YutaroOgawa** [comment]
@KENJI-JIN さま

ご指摘をいただき、ありがとうございます。
こちら式変形の記載が誤っていました。
訂正案でいただいた通りでございます。

以下訂正させていただきます。

ーーーーーーーーーーーーーーーーーーーーー
訂正範囲：p. 82　4行目～18行目の数式展開
ーーーーーーーーーーーーーーーーーーーーー

P.81 終わり
Sigma_x P(Y=y | Z=z, X=x)P(X=x)

に対して、条件付き確率を同時確率にする（Zについて）なので、

p. 82 4行目

P(Y=y | X=x, Z=z) = P(Y=y, Z=z | X=x) / P(Z=z | X=x)

となり、

P(Y=y | X=x, Z=z) P(X=x)は、

P(Y=y, Z=z | X=x) P(X=x) / P(Z=z | X=x)
となります。

そして分子をＸについて条件付き確率から同時確率へと変換すると

P(Y=y, Z=z | X=x) P(X=x) = P(Y=y, X=x, Z =z)
となります。

よって、P(Y=y | Z=z, X=x)P(X=x)は、

P(Y=y, X=x, Z =z) / P(Z=z | X=x)

となります。

ーーーーーーーーーーーーーーーーーーーーー

本Issueに誤植ラベルを貼り、今後修正機会に修正いたします。

非常に重要な部分の式展開が誤っており、大変申し訳ございません。

貴重なご指摘をいただき、心より感謝申し上げます。
誠にありがとうございます。

今後ともどうぞ宜しくお願い致します。

**Comment by KENJI-JIN** [comment]
迅速なご回答ありがとうございます。上記の内容で理解できました。
