### ISSUE TITLE
P84についての質問です。【訂正：0.1、-1、-4 にほぼ近い係数が求まっており、】

### ISSUE THREAD

**Issue by KENJI-JIN** [YutaroOgawa/causal_book#25]
P84の最初の行に
正しい答えである、0.1、－１、－３にほぼ近い係数が求まっており、
と書いてありますが、
-40+noiseなので、-40 * 0.1 = -4で
0.1、－１、**－４**
だと思うのですが、-3はどこから出てきた数字でしょうか？

**Comment by YutaroOgawa** [comment]
@KENJI-JIN さま

ありがとうございます。
こちら、完全に私の単なるミスです。大変申し訳ございません。
ご指摘の通り、-4が正しいです。

＝＝＝＝＝＝＝＝＝
p.84 最初の行
＝＝＝＝＝＝＝＝＝
（修正前）正しい答えである、0.1、-1、-3 にほぼ近い係数が求まっており、

（修正後）正しい答えである、0.1、-1、-4 にほぼ近い係数が求まっており、



本Issueに誤植ラベルを貼り、他の読者の皆様の参考にさせてください。
また、増刷されることがありましたら、書面も修正させていただきます。
丁寧に本書を活用いただき、誠にありがとうございます。

**Comment by KENJI-JIN** [comment]
迅速なご回答ありがとうございます。

**Comment by kkkkkkkoji** [comment]
（修正前）の0.1、-1、-3 の方が正しいと思うのですが、いかがでしょうか？
sigmoidの中身が x_1 + (1 - x_2) ＊10 - 40 + noise ですので、変形したら x_1 - 10＊x_2 - 30 + noise になりませんでしょうか？

**Comment by YutaroOgawa** [comment]
@kkkkkkkoji さま

ご指摘ありがとうございます。頂いた通りでした。私が早とちりして誤った回答をしております。

新たなIssueで誤植訂正として、以下と同内容を掲載いたします。

重要なご指摘をいただき、誠にありがとうございます。


---




4.2 逆確率重み付け法（IPTW）による因果推論
https://github.com/YutaroOgawa/causal_book/blob/master/4_2_iptw.ipynb

において、

```python
# シグモイド関数に入れる部分
z_base = x_1 + (1-x_2)*10 - 40 + 5*e_z

# シグモイド関数を計算
z_prob = expit(0.1*z_base)
```

であるため、

シグモイドの中身は
```1*x_1 - 10*x_2 -30```
に0.1をかけ算したものになるので、0.1、-1.0、-3.0 でした。。。

が正しいです。失礼いたしました。
